### ISSUE TITLE
Wish: ADD button

### ISSUE THREAD

**Issue by marcogruebler** [Diuxtros/BlacklistWarden#1]
This needs an ADD button.
What if you just reloaded your Interface for any reason - cannot even add new entry from Ignore List.
Maybe this might also be worth considering: (auto)-Import from Ignore List.
"Add" name button in List view.
Chat command to add ppl to the list.

**Comment by Diuxtros** [comment]
I wanted to avoid people typing names simply to avoid user errors like typos but youre right, sometimes theres no other choice, ill try to get it done this week.
